// Generated by LiveScript 1.5.0
(function(){
  window.bindAll = function(){
    var d, url;
    d = $('#x').val();
    $('#latex').html(toLatex(d));
    url = 'http://chart.apis.google.com/chart?chs=60&cht=tx&chl=' + toLatex(d);
    $('#view').html('<img class ="tex" src = "' + url + '" />');
  };
  $('#x').on('keypress', window.bindAll());
  $('#x').on('change', window.bindAll());
}).call(this);
